//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp_MoPhone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleDetail
    {
        public int Id { get; set; }
        public string NameAction { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<int> IdRole { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual User User { get; set; }
    }
}
